config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  
  resources :todo_items do
      member do
        patch :complete
      end
    resources :users, only: [:show]
  end

  root "welcome#index"

  get 'about' => 'welcome#about'
  
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :user

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  def create
    @todo_item = TodoItem.new(set_todo_item_params)
    if @todo_item.save
      flash[:success] = "To-Do Item was saved successfully."
    else
      flash[:error] = "To-Do Item could not be deleted."
      return render action: :new
    end
    redirect_to todo_items_path
  end

  def index
    @todo_items = TodoItem.all
  end

  def new
    @todo_item = TodoItem.new
  end

  def edit
  end

  def destroy
    if TodoItem.find(params[:id]).destroy
       flash[:success] = "To-Do Item item was deleted."
    else
      flash[:error] = "To-Do Item could not be deleted."
    end
    redirect_to todo_items_path
  end

  private

 def set_todo_item_params
     params.require(:todo_item).permit(:content, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @todos = @user.todos.visible_to(current_user)
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "user information updated!"
      redirect edit_user_registration_path
    else
      flash[:error] = "Invalid user information."
      redirect_to edit_user_registration_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlocItOff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <ul class="nav nav-tabs">
      <li><%= link_to "BlocItOff", root_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_items, TodoItem.new]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<%= form_for [@todo_item] do |f| %>
   <%= form_group_tag(todo_item[:content]) do %>
     <%= f.text_field :content, class: 'form-control', placeholder: "Edit To-Do Item" %>
   <% end %>
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/todo_items/about.html.erb
<h1>About BlocItOff</h1>

<p><h4>BlocItOff is a self-destrucitng ToDo list. Items added will be automatically deleted after seven days or by marking them complete</h4></p>

<%= link_to "BlocItOff Home Page", root_path %> 

app/views/todo_items/destroy.js.erb
<% if @todo_item.destroyed? %>
  $('#todo_item-' +<%= @todo_item.id %>).hide();
  $('.js-todo_items-count').html("<%= pluralize(@todo_item.user.todo_items.count, 'todo_item') %>");
<% else %>
  ('todo_item-' +<%= @todo_item.id %>).prepend("div class='alert alert-danger')<%= flash[:error] %></div>");
<% end %>

app/views/todo_items/edit.html.erb
<h1>Edit Todo Item</h1>

<% render partial: "todo_item" %>

<%= link_to 'Back', todo_item_path %>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Items:</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.content %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
        <td><%= link_to "Item Completed/Delete", todo_item, method: :delete, class: 'glyphicon glyphicon-ok' %></td>
        <td><%= todo_item.days_left %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo Item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<h1>Create New To-Do</h1>

<%= render 'form' %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<div id="todo_items_wrapper">
  <%= render "todo_items/todo_item"%>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="row">
  <div class="col-md-8">
     <div class="media-body">
        <h2 class="media-heading"><%= user.name %></h2>
     </div>
  </div>
</div>
 <div class="row">
   <div class="tabbable tabs-left">
     <ul class="nav nav-tabs">
       <li class="active"><a href="#todos" data-toggle="tab">To-Do's</a></li>
     </ul>
    </div>
  </div>
  

app/views/welcome/about.html.erb
<h1>About BlocItOff</h1>

<p><h4>BlocItOff is a self-destrucitng ToDo list. Items added will be automatically deleted after seven days or by marking them complete</h4></p>

<%= link_to "BlocItOff Home Page", root_path %> 

app/views/welcome/index.html.erb
<h1>Welcome to BlocItOff</h1>
<p>...A self-destrucing To-Do List/p>